---
- name: Add fish repository
  apt_repository:
    repo: "ppa:fish-shell/release-3"
    state: present

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

- name: Install required packages
  apt:
    name:
    - net-tools
    - magic-wormhole
    - jq
    - fish
