---
- name: Create service group
  group: "name=cheqd system=yes"

- name: Create service user
  user: "name=cheqd home=/home/cheqd system=yes group=cheqd shell=/bin/bash"

- name: Change user folder to more permissive
  file: "path=/home/cheqd mode=0755"

- name: Set .cheqdnode directory owner and group to cheqd
  file:
    path: /home/cheqd/.cheqdnode/
    owner: cheqd
    group: cheqd
    state: directory
    recurse: yes

- name: Creates config directory
  become: yes
  become_user: cheqd
  file:
    path: /home/cheqd/.cheqdnode/config
    state: directory

- name: Install cheqd
  apt:
    deb: https://github.com/cheqd/cheqd-node/releases/download/v{{ version }}/cheqd-node_{{ version }}_amd64.deb

- name: Download the genesis file
  get_url:
    url: https://raw.githubusercontent.com/cheqd/cheqd-node/main/persistent_chains/{{ network }}/genesis.json
    dest: /home/cheqd/.cheqdnode/config/genesis.json
    force: yes
  become: yes
  become_user: cheqd
  when: new_account

- name: Store seeds inside an environment variable
  uri:
    url: https://raw.githubusercontent.com/cheqd/cheqd-node/main/persistent_chains/mainnet/seeds.txt
    return_content: yes
  register: seeds
  become: yes
  become_user: cheqd
  when: new_account

# TBD
# - name: Register validator ID
#   command:
#   when: new_account and host == "validator"
#   register: validator_id

# - name: Register seed ID
#   command:
#   when: new_account and host == "seed"
#   register: seed_id

# - name: Register sentry ID
#   command:
#   when: new_account and host == "sentry"
#   register: sentry_id 

- name: Update the config.toml file
  become: yes
  become_user: cheqd
  template: 
    src: config.toml.j2 
    dest: /home/cheqd/.cheqdnode/config/config.toml

- name: Update the app.toml file
  become: yes
  become_user: cheqd
  template:
    src: app.toml.j2
    dest: /home/cheqd/.cheqdnode/config/app.toml

# TBD
# - name: Download snapshot data
  # uri:
    # url: https://google.com
  # dest: /home/cheqd/.cheqdnode/data
  