name: "Lint"
on:
  workflow_call:
defaults:
  run:
    shell: bash


jobs:

  sh-euox-pipefail-check:
    name: "Shell pipefail check"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Run 'set -euox pipefail' check
        run: bash ./.github/scripts/ensure_set_euox_pipefail.sh
  
  md-link-check:
    name: "Broken Markdown links"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Run Markdown link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: '.github/linters/mlc_config.json'
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'

    name: Linter for Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tfsec Analysis
        uses: aquasecurity/tfsec-pr-commenter-action@v1.0.5
        with:
          tfsec_args: --soft-fail 
          github_token: ${{ github.token }}

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          config_file: .checkov.yaml

  super-lint:
    name: "Super Linter"
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Required to fetch version
    
    - name: Run Super Linter
      uses: github/super-linter/slim@v4
      env:
        IGNORE_GITIGNORED_FILES: true
        DEFAULT_BRANCH: main
        LINTER_RULES_PATH: '.github/linters'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LOG_LEVEL: WARN
        VALIDATE_ALL_CODEBASE: true
        MULTI_STATUS: true

        VALIDATE_BASH: true
        VALIDATE_DOCKERFILE_HADOLINT: true
        VALIDATE_GITHUB_ACTIONS: true
        # VALIDATE_JAVASCRIPT_ES: true
        VALIDATE_JSON: true
        VALIDATE_MARKDOWN: true
        VALIDATE_OPENAPI: true
        VALIDATE_TERRAFORM_TFLINT: true
        VALIDATE_TERRAGRUNT: true
        # VALIDATE_TSX: true
        # VALIDATE_TYPESCRIPT_ES: true
        VALIDATE_XML: true
        VALIDATE_YAML: true
