name: "Release"
on:
  workflow_call:
defaults:
  run:
    shell: bash


jobs:
  
  generate-docs:
    name: "Generate Terraform Docs"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Render Terraform docs
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: ./terraform/digital-ocean,./terraform/hetzner
        output-file: README.md
        output-method: inject
        git-push: true
